gc()
rm(list = ls())

#####
# preparations
#####
new.pkgs <- c("stringr", "tidyverse", "dplyr", 
              "ggplot2", "stringdist", "igraph",
              "this.path", "argparse")
new.bioc.pkgs <- c("Biostrings", "msa")
for (pkg in new.pkgs){
  if (pkg %in% installed.packages() == FALSE){
    install.packages(pkg)
  }
}
for (pkg in new.bioc.pkgs){
  if (pkg %in% installed.packages() == FALSE){
    BiocManager::install(pkg)
  }
}

# *****
# libraries
library(stringr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringdist)
library(igraph)
library(Biostrings)
library(msa)
library(this.path)
library(argparse)

# get current dir. 
# path.to.main.src <- "/home/hieunguyen/CRC1382/src_2023/bcrtree_pipeline" # my local dir
path.to.main.src <- this.dir()
source(file.path(path.to.main.src, "VDJ_helper_functions_for_bulkBCR.R"))
ref.gene.config <- file.path(path.to.main.src, "ref_gene_config.R")

#####----------------------------------------------------------------------#####
# ***** INPUT ARGUMENTS *****
#####----------------------------------------------------------------------#####
# examples
# fetch all input files generated by the MIXCR pipeline
# this path should contain all samples involved in the analysis. 
# path.to.mixcr.output <- file.path(path.to.main.src, "output/mixcr_pipeline_output/mid_based_output")
# path.to.save.fasta <- file.path(path.to.main.src, "output", "fasta_for_GCTree_pipeline")
# path.to.save.output <- file.path(path.to.main.src, "output", "preprocessed_files")
# 
# PROJECT <- "testPipeline"
# re_define_clone_cluster <- TRUE
# rerun <- FALSE
# savefile <- TRUE
# verbose <- TRUE
# save_fasta <- TRUE
# define.clone.clusters <- FALSE
# ref.gene <- "IMGT"
# mouse.id <- "testMouse"

# argparse input args
parser <- ArgumentParser()
parser$add_argument("--input", action="store",
                    required = TRUE,
                    help="path to output data obtained from mixcr pipeline")
parser$add_argument("--fasta", action="store",
                    required = TRUE,
                    help="path to save FASTA files, which will be used as input to GCTree pipeline")
parser$add_argument("--processed_output", 
                    action="store",
                    required = TRUE,
                    help="path to save intermediate output data")
parser$add_argument("--PROJECT", 
                    action="store",
                    required = TRUE,
                    help="PROJECT name")
parser$add_argument("--re_define_clone_cluster", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. TRUE = re-define the clone cluster based on sequence similarity")
parser$add_argument("--rerun", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. if FALSE, do not re-run the script if output data exists")
parser$add_argument("--savefile", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. if TRUE: save file output to output dir.")
parser$add_argument("--verbose", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. if TRUE: show script running progress")
parser$add_argument("--save_fasta", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. if TRUE: save FASTA files")
parser$add_argument("--define_clone_clusters", action="store_true", 
                    type = "logical",
                    required = TRUE,
                    help="TRUE or FALSE. if TRUE: define sub-clusters in each clone based on sequence similarity")
parser$add_argument("--ref_gene", action="store", 
                    required = TRUE,
                    help="IMGT or 10x")
parser$add_argument("--mouse_id", action="store", 
                    required = TRUE,
                    help="Name of the mouse in this experiment - name of the pooled sequence tree.")

args <- parser$parse_args()

path.to.mixcr.output <- args$input
path.to.save.fasta <- args$fasta
path.to.save.output <- args$processed_output
PROJECT <- args$PROJECT
re_define_clone_cluster <- args$re_define_clone_cluster
rerun <- args$rerun
savefile <- args$savefile
verbose <- args$verbose
save_fasta <- args$save_fasta
define.clone.clusters <- args$define_clone_clusters
ref.gene <- args$ref_gene
mouse.id <- args$mouse_id

#####----------------------------------------------------------------------#####
##### MAIN RUN
#####----------------------------------------------------------------------#####
dir.create(path.to.save.fasta, showWarnings = FALSE, recursive = TRUE)
dir.create(path.to.save.output, showWarnings = FALSE, recursive = TRUE)

clone.output <- run_preprocessing_all_bulk_VDJ_data(
  path.to.mid.output = path.to.mixcr.output, 
  path.to.save.output = path.to.save.output,
  PROJECT = PROJECT,
  thres = thres, 
  thres.dis = thres.dis,
  savefile = savefile,
  verbose = verbose,
  rerun = rerun,
  define.clone.clusters = define.clone.clusters
)  

clonesets <- clone.output$clonesets

input.clonesets <- clonesets

# ***** generate FASTA
output.all.fasta <- generate_fasta(
  clonesets = input.clonesets, 
  mouse.id = mouse.id,
  path.to.save.output = file.path(path.to.save.fasta), 
  ref.gene = ref.gene, 
  ref.gene.config = ref.gene.config,
  PROJECT = PROJECT,
  thres = 0.85,
  thres.dis = 0.15,
  save_fasta = save_fasta,
  re_define_clone_cluster = re_define_clone_cluster,
  path.to.save.samplesheet = path.to.main.src)

# EOF