gc()
rm(list = ls())

new.pkgs <- c("stringr", "tidyverse", "dplyr", "ggplot2", "stringdist", "igraph")
new.bioc.pkgs <- c("Biostrings", "msa")
for (pkg in new.pkgs){
  if (pkg %in% installed.packages() == FALSE){
    install.packages(pkg)
  }
}
for (pkg in new.bioc.pkgs){
  if (pkg %in% installed.packages() == FALSE){
    BiocManager::install(pkg)
  }
}

# *****

library(stringr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringdist)
library(igraph)
library(Biostrings)
library(msa)

PROJECT <- "testPipeline"
path.to.main.src <- "/home/hieunguyen/CRC1382/src_2023/bcrtree_pipeline"
source(file.path(path.to.main.src, "VDJ_helper_functions_for_bulkBCR.R"))

ref.gene.config <- file.path(path.to.main.src, "ref_gene_config.R")

# fetch all input files generated by the MIXCR pipeline
# this path should contain all samples involved in the analysis. 

path.to.mixcr.output <- file.path(path.to.main.src, "output/mixcr_pipeline_output/mid_based_output")
path.to.save.fasta <- file.path(path.to.main.src, "output", "fasta_for_GCTree_pipeline")
path.to.save.output <- file.path(path.to.main.src, "output", "preprocessed_files")

dir.create(path.to.save.fasta, showWarnings = FALSE, recursive = TRUE)
dir.create(path.to.save.output, showWarnings = FALSE, recursive = TRUE)

re_define_clone_cluster <- TRUE
rerun <- FALSE
savefile <- TRUE
verbose <- TRUE
save_fasta <- TRUE
define.clone.clusters <- FALSE
ref.gene <- "IMGT"
mouse.id <- "testMouse"

clone.output <- run_preprocessing_all_bulk_VDJ_data(
  path.to.mid.output = path.to.mixcr.output, 
  path.to.save.output = path.to.save.output,
  PROJECT = PROJECT,
  thres = thres, 
  thres.dis = thres.dis,
  savefile = savefile,
  verbose = verbose,
  rerun = rerun,
  define.clone.clusters = define.clone.clusters
)  

clonesets <- clone.output$clonesets

input.clonesets <- clonesets
# ***** generate FASTA
output.all.fasta <- generate_fasta(
  clonesets = input.clonesets, 
  mouse.id = mouse.id,
  path.to.save.output = file.path(path.to.save.fasta, "all_samples"), 
  ref.gene = ref.gene, 
  ref.gene.config = ref.gene.config,
  PROJECT = PROJECT,
  thres = 0.85,
  thres.dis = 0.15,
  save_fasta = save_fasta,
  re_define_clone_cluster = re_define_clone_cluster)
